*** Variables ***

${SELECT_PRODUCT}               css=#center_column > ul > li > div > div.left-block > div > a.product_img_link > img
${ADD_CART}                     name=Submit
${PROCEED_TO_CHECKOUT}          css=#layer_cart > div.clearfix > div.layer_cart_cart.col-xs-12.col-md-6 > div.button-container > a
${SUMMARY_PROCEED}              css=#center_column > p.cart_navigation.clearfix > a.button.btn.btn-default.standard-checkout.button-medium